apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-workers-secret
  namespace: default
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: AZURE_STORAGE_ACCOUNT_DATUM
  AZURE_STORAGE_ACCESS_KEY: AZURE_STORAGE_ACCESS_KEY_DATUM
  AZURE_CONTAINER: online-models
  MASTER: sgdecoding-online-scaled-master
  NAMESPACE: ntu-sgdecoding-online-scaled
  RUN_FREQ: FOREVER # for run_worker.yaml (testing) will override this with value=ONCE
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models


---

apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-master-secret
  namespace: default
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: AZURE_STORAGE_ACCOUNT_DATUM
  AZURE_STORAGE_ACCESS_KEY: AZURE_STORAGE_ACCESS_KEY_DATUM
  AZURE_CONTAINER: online-models
  NAMESPACE: ntu-sgdecoding-online-scaled
  MASTER: sgdecoding-online-scaled-master
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models
