apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-workers-secret
#  namespace: default
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: ntuscaledstorage2
  AZURE_STORAGE_ACCESS_KEY: MI4sQGf5Pr+aw7kAb3WUdBhr7NscB6nJBQQzOujufuhmvrDLtiWxUjH3f3yggvem00Izhn5sR3waZJxbx6V6yg==
  AZURE_CONTAINER: online-models
  MASTER: sgdecoding-online-scaled-master
  NAMESPACE: default
  RUN_FREQ: FOREVER # for run_worker.yaml (testing) will override this with value=ONCE
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models
  IMAGE: abcd


---

apiVersion: v1
kind: Secret
metadata:
  name: environment-variables-master-secret
#  namespace: default
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT: ntuscaledstorage2
  AZURE_STORAGE_ACCESS_KEY: MI4sQGf5Pr+aw7kAb3WUdBhr7NscB6nJBQQzOujufuhmvrDLtiWxUjH3f3yggvem00Izhn5sR3waZJxbx6V6yg==
  AZURE_CONTAINER: online-models
  NAMESPACE: default
  MASTER: sgdecoding-online-scaled-master
  ENABLE_HTTPS: "false"
  MODELS_FILESHARE_SECRET: models-files-secret
  MODELS_SHARE_NAME: online-models
  IMAGE: abcd