models:
  SingaporeCS_0519NNET3: 1
  English_0919_8k: 0
  
image:
  repository: registry.gitlab.com/benjaminc8121/ntu_asr/staging:latest
  tag: latest
  pullPolicy: Always
  pullSecrets: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080
  resourceGroup: ntu-online-scaled
#  loadBalancerIP: 20.44.218.143
  enablehttps: false

commands:
  master:
    - '"/home/appuser/opt/tini"' 
    - '"--"'
    - '"/home/appuser/opt/start_master.sh"'
  worker:
  # see _helpers.tpl on how full command constructed
    pre:
      - '"/home/appuser/opt/tini"' 
      - '"--"'
      - '"/home/appuser/opt/start_worker.sh"'
fileshare:
  secretName: models-files-secret
  shareName: online-models

