---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: NFS_CLUSTER_IP
    path: "/"
