version: '3.7'

services:
  test_asr:
    build: ./
    command: bash -c "python3 python_dir/client_3_ssl.py -u ws://$MASTER_SERVICE_IP/client/ws/speech -r 32000 -t abc --model=SingaporeCS_0519NNET3 wave_dir/episode-1-introduction-and-origins.wav"

# docker-compose up -e MASTER_SERVICE_IP=$(kubectl get svc -n ntuasr-production-azure $MASTER_SERVICE --output jsonpath='{.status.loadBalancer.ingress[0].ip}')