apiVersion: v1
kind: PersistentVolume
metadata:
 name: jenkins
 #annotations:
  #pv.beta.kubernetes.io/gid: "1000"
spec:
 capacity:
   storage: 5Gi
 accessModes:
 - ReadWriteOnce
 azureFile:
   secretName: storage-connection
   secretNamespace: jenkins
   shareName: jenkins-share
   readOnly: false
 claimRef:
   name: jenkins-pvc
   kind: PersistenVolumeClaim
   namespace: jenkins
 persistentVolumeReclaimPolicy: Retain