apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-azurefiles
  labels:
    usage: models-azurefiles
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: models-files-secret
    shareName: online-models
    readOnly: true
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl