models:
  SingaporeCS_0519NNET3: 1
  SingaporeMandarin_0519NNET3: 0
  
image:
  repository: registry.gitlab.com/benjaminc8121/ntu_asr/staging:latest
  pullPolicy: Always
  pullSecrets: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080
  resourceGroup: ntu-online-scaled
#  loadBalancerIP: 20.97.51.248
  enablehttps: false

commands:
  master:
    - '"/home/appuser/opt/tini"' 
    - '"--"'
    - '"/home/appuser/opt/start_master.sh"'
  worker:
  # see _helpers.tpl on how full command constructed
    pre:
      - '"/home/appuser/opt/tini"' 
      - '"--"'
      - '"/home/appuser/opt/start_worker.sh"'
fileshare:
  claimName: fileserver-claim
